In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
import plotly_express as px

In [ ]:
bosanma_tr1=pd.read_excel("/Users/adnuka/Desktop/GitHub-Projects/eslerin-bosanma-nedeni/tr1_bosanma.xls")

In [ ]:
bosanma_tr1 = bosanma_tr1.fillna(method='ffill', axis=0)

In [ ]:
bosanma_tr1.groupby(['bolge',"yas_farki","yil"])['bosanma_sayisi'].pct_change()

In [ ]:
bosanma_tr1['pct'] = bosanma_tr1.sort_values('yil').groupby(['bolge', 'yas_farki']).bosanma_sayisi.pct_change()

In [ ]:
bosanma_tr1["bosanma_yuzde"]=bosanma_tr1["pct"]*100

In [ ]:
yasa_gore=sns.relplot(data=bosanma_tr1, x='yil', y='bosanma_yuzde', row='yas_farki', kind='line',height=8,legend="auto")
yasa_gore.savefig("yas_gore", dpi=300)

In [ ]:
bolgeye_gore=sns.relplot(data=bosanma_tr1, x='yil', y='bosanma_yuzde', row='bolge', kind='line',height=8,legend="auto")
bolgeye_gore.savefig("bolgeye_gore", dpi=300)

In [ ]:
bosanma_tr1.drop('pct', inplace=True,axis=1)

In [ ]:
bosanma_tr1.groupby('yil').agg({'bosanma_sayisi':'sum',
                                'bosanma_yuzde':'mean'}).reset_index()

In [119]:
bosanma_tr1.groupby(['yil',"bolge"]).agg({'bosanma_sayisi':'sum',
                                'bosanma_yuzde':'mean'}).reset_index().sort_values('bosanma_yuzde',ascending=False).head(5)

      yil                  bolge  bosanma_sayisi  bosanma_yuzde
212  2018  Kuzeydoğu Anadolu-TRA            1705      31.667887
226  2019   Ortadoğu Anadolu-TRB            3351      28.444505
106  2009   Ortadoğu Anadolu-TRB            2153      22.388144
142  2012   Ortadoğu Anadolu-TRB            2176      21.194126
211  2018  Güneydoğu Anadolu-TRC            6784      19.262579

In [120]:
bosanma_tr1.groupby(["yil","yas_farki"]).agg({'bosanma_sayisi':'sum',
                                'bosanma_yuzde':'mean'}).reset_index().sort_values('bosanma_yuzde',ascending=True)

      yil                             yas_farki  bosanma_sayisi  bosanma_yuzde
144  2011          Eşlerin yaş farkı:Bilinmeyen            2930     -35.563722
104  2008        Eşlerin yaş farkı:Yaşları Eşit            6416     -30.991342
270  2020          Eşlerin yaş farkı:Bilinmeyen            2887     -19.873956
264  2020                   Eşlerin yaş farkı:4           11782     -14.549865
261  2020                 Eşlerin yaş farkı:11+           11892     -14.547585
..    ...                                   ...             ...            ...
9    2001                   Eşlerin yaş farkı:8            4286            NaN
10   2001                   Eşlerin yaş farkı:9            3290            NaN
11   2001  Eşlerin yaş farkı:Damadın Yaşı Küçük           13895            NaN
12   2001        Eşlerin yaş farkı:Yaşları Eşit            9315            NaN
102  2008          Eşlerin yaş farkı:Bilinmeyen            4605            NaN

[273 rows x 4 columns]

In [124]:
bosanma_tr1.groupby(["bolge","yas_farki"]).agg({'bosanma_sayisi':'sum',
                                'bosanma_yuzde':'mean'}).reset_index().sort_values('bosanma_yuzde',ascending=True).head(10)

,bolge,yas_farki,bosanma_sayisi,bosanma_yuzde
151,Ortadoğu Anadolu-TRB,Eşlerin yaş farkı:Bilinmeyen,1201,-6.506998
137,Orta Anadolu-TR7,Eşlerin yaş farkı:Bilinmeyen,3579,-6.040768
109,Güneydoğu Anadolu-TRC,Eşlerin yaş farkı:Bilinmeyen,3351,-5.835648
67,Doğu Karadeniz-TR9,Eşlerin yaş farkı:Bilinmeyen,1055,-5.210785
39,Batı Karadeniz-TR8,Eşlerin yaş farkı:Bilinmeyen,1596,-4.214432
25,Batı Anadolu-TR5,Eşlerin yaş farkı:Bilinmeyen,5172,-3.614060
95,Ege-TR3,Eşlerin yaş farkı:Bilinmeyen,6761,-3.548544
123,Kuzeydoğu Anadolu-TRA,Eşlerin yaş farkı:Bilinmeyen,625,-3.266435
11,Akdeniz-TR6,Eşlerin yaş farkı:Bilinmeyen,7983,-1.351226
139,Orta Anadolu-TR7,Eşlerin yaş farkı:Yaşları Eşit,9868,-1.121237

In [127]:
bosanma_tr1[bosanma_tr1['yil']==2020].groupby(["bolge","yas_farki"]).agg({'bosanma_sayisi':'sum',
                                'bosanma_yuzde':'mean'}).reset_index().sort_values('bosanma_yuzde',ascending=False).head(10)

,bolge,yas_farki,bosanma_sayisi,bosanma_yuzde
130,Orta Anadolu-TR7,Eşlerin yaş farkı:3,653,22.284644
122,Kuzeydoğu Anadolu-TRA,Eşlerin yaş farkı:9,82,18.840580
53,Batı Marmara-TR2,Eşlerin yaş farkı:Bilinmeyen,115,10.576923
112,Kuzeydoğu Anadolu-TRA,Eşlerin yaş farkı:1,117,10.377358
135,Orta Anadolu-TR7,Eşlerin yaş farkı:8,426,9.511568
65,Doğu Karadeniz-TR9,Eşlerin yaş farkı:8,167,9.150327
63,Doğu Karadeniz-TR9,Eşlerin yaş farkı:6,243,8.482143
104,Güneydoğu Anadolu-TRC,Eşlerin yaş farkı:5,601,2.735043
138,Orta Anadolu-TR7,Eşlerin yaş farkı:Damadın Yaşı Küçük,867,2.120141
62,Doğu Karadeniz-TR9,Eşlerin yaş farkı:5,271,1.879699

array(['Akdeniz-TR6', 'Batı Anadolu-TR5', 'Batı Karadeniz-TR8',
       'Batı Marmara-TR2', 'Doğu Karadeniz-TR9', 'Doğu Marmara-TR4',
       'Ege-TR3', 'Güneydoğu Anadolu-TRC', 'İstanbul-TR1',
       'Kuzeydoğu Anadolu-TRA', 'Orta Anadolu-TR7',
       'Ortadoğu Anadolu-TRB'], dtype=object)